language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

branches:
  only:
    master

addons:
  code_climate:
    repo_token:
      secure: "j6y4BlvuZK9IOcRKVEfXObR+sXWZhaD3/ovPCfeuM2Sbu0QhQC4g9T7XqQeyHI8w8vMrP4/IMQKBpDX0KY63vPMO4rsxFqm4MqD5OBM/HepY2W+haoT7Bj6VPLyC3UgN8n0kYTOeCe0kxkdhGrf7XXtNA3qnK0/IqjoATy3mck/UvjAQ64kAw37XenpPQGRZnGz0DjPHHu78oq3BOUyPJJ+7gTAE2MtCgNw/8f5VpzvQGBa5ZrpyR0comvIhWJjdzsMllfVl0BEpMawitVNhis+jYSrkzUXcI2xWahHHh9ba8176rPX6M+CSQd1FQetw9+XUl+C89AXCTXpnxa6FnbD1YH1rxNgqzcK2mCVfKYq0JMeX8gZfFqpVhgco7j+Zm6OYMwA4GqBfSpcs/JMZO6H20KzRhruo4dE7Lh8tFokGLrIrOVrYjneMCwnM38u8bwYlsFOTd6Uj+92NbBc6GFctEd38Q9L20fv/4feNHEJWXS1Z6yXJYNrYk3bw2IigS1PwyjnhC0ntNKIA19/VETFLRVUeDGC2pOqChs1EIOiD6TmpX1hp2GbijXXbwY0LpEp8+XHdxl4uV6ErkK/KC2iRtqXPy0XMXNSqEwJvJw4JRzlDhHeNfB+SNBw9gq6ujMwleLW+YzNa4YqfSQqKzkqr/OtGk30qMeRRX4/4/Mo="

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

install:
  - travis_retry composer install

script:
  - composer travis

after_script:
  - vendor/bin/test-reporter